name: Game CI

on: [push, pull_request]

jobs:
    checkLicense:
        name: Check for the Unity License
        runs-on: ubuntu-latest
        setps:
            - name: Fail - No license
            if: ${{ !startWith(env.UNITY_LICENSE, '<') }}
            run: exit 1
            
